/* Author:          McKelvy, James Markus
 * CLID:            jmm0468
 * Class:           CMPS360
 * Assignment:      proj2
 * Date Assigned:   Thursday, 22 March 2007, 12:00 AM
 * Due date:        Monday, 16 April 2007, 08:00 PM
 * Description:
 * This is a module that allows someone to create a test. It allows you to set
 * the type of question and the worth of the question. A help module is included
 * to show the user how to format each type of question so that the program knows
 * how to interpret them and display them correctly to a student.
*/	

package proj2;

import java.io.*;
/**
 * This is a module that allows someone to create a test. It allows you to set
 * the type of question and the worth of the question. A help module is included
 * to show the user how to format each type of question so that the program knows
 * how to interpret them and display them correctly to a student.
 * @author  mark
 */
public class Create extends javax.swing.JFrame {
    
    /**
     *Parent window, set to visible when this one is disposed.
     */
    private javax.swing.JFrame myparent;
    
    /**
     *Filename of created test.
     */
    private String filename;
    
    /**
     *A writer for the test file.
     */
    private PrintWriter writer;
    
    /**
     *Keeps track of the total number of questions created.
     */
    private int total = 0;
    
    /** Creates new form Create */
    public Create(javax.swing.JFrame parent, String filename) {
        myparent = parent;
        this.filename = filename;
        mainInitialization();
    }

    /**
     *Handles opening of writer. Initializes gui components. Sets everything else
     *up.
     */
    private void mainInitialization(){
        if(openFile() == false){
            javax.swing.JOptionPane.showMessageDialog(this, "Error opening file for writing. Questions will not be saved to file.");
        }
        initComponents();
        jPanel1.setVisible(false);
        saveQuestion.setVisible(false);
        jLabel7.setText(String.valueOf(total));
        centerApp();
        this.setVisible(true);
    }
    
    /**
     *Opens the file for writing.
     */
    public boolean openFile(){
        boolean success = true;
        writer = null;
        try{
            writer = new PrintWriter(new BufferedWriter(new FileWriter(filename)));            
        }catch(Exception e){
            e.printStackTrace();
            success = false;
        }
        return success;
    }
    
     /**
     *Centers the window on the screen.
     */
    private void centerApp(){
        java.awt.Dimension screenSize = this.getToolkit().getScreenSize();
        java.awt.Dimension appSize = this.getSize();
        this.setLocation((screenSize.width - appSize.width) / 2,(screenSize.height - appSize.height) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        newQuestion = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        saveQuestion = new javax.swing.JButton();
        help = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        newQuestion.setText("New Question");
        newQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show(evt);
            }
        });

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setText("Type");

        jLabel3.setText("Points");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choice", "Blank", "Essay" }));

        jTextField1.setColumns(5);
        jTextField1.setText("10");

        jLabel4.setText("Question");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Click 'Help' for information on formatting questions.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Answer");

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("Please use lower case for single worded answers.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        saveQuestion.setText("Save Question");
        saveQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveQuestion(evt);
            }
        });

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        jLabel6.setText("Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(help)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quit))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newQuestion)
                    .addComponent(quit)
                    .addComponent(saveQuestion)
                    .addComponent(help)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Called to produce the help dialog for the user.
     */
    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        (new CreateHelp()).setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    /**
     *Quit button pressed, calls quit()
     */
    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        quit();
    }//GEN-LAST:event_quitActionPerformed

    /**
     *Closes open writer. Disposes this window. Sets the parent visible.
     */
    private void quit(){
        writer.close();
        dispose();
        myparent.setVisible(true);
    }
    
    /**
     *Called when the window is closing. Calls quit()
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        quit();
    }//GEN-LAST:event_formWindowClosing

    /**
     *Saves a question to the file.
     */
    private void SaveQuestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveQuestion
        saveQuestion.setVisible(false);
        //jPanel1.setVisible(false);
        writer.println(((String)(jComboBox1.getSelectedItem())).toLowerCase());
        writer.println(Integer.parseInt(jTextField1.getText()));
        writer.println("--" + jTextArea1.getText());
        writer.println("--" + jTextArea2.getText());
        writer.flush();
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextField1.setText("10");
        jTextField1.setColumns(5);
        jLabel7.setText(String.valueOf(++total));
        jTextField1.setEditable(false);
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jComboBox1.setEditable(false);
    }//GEN-LAST:event_SaveQuestion

    private void Show(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show
        if(!jTextArea1.getText().equals("")){
            int choice = javax.swing.JOptionPane.showConfirmDialog(this, "Would you like to save this question?");
            if(choice == 0)
                SaveQuestion(evt);
            else if(choice == 2)
                return;
        }
        saveQuestion.setVisible(true);
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextField1.setText("10");
        jTextField1.setColumns(5);
        jTextField1.setEditable(true);
        jTextArea1.setEditable(true);
        jTextArea2.setEditable(true);
        jComboBox1.setEditable(true);
        if(!jPanel1.isVisible()){
            jPanel1.setVisible(true);
        }
        
    }//GEN-LAST:event_Show

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton help;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton newQuestion;
    private javax.swing.JButton quit;
    private javax.swing.JButton saveQuestion;
    // End of variables declaration//GEN-END:variables
    
}
